---
name: ğŸªŸ Windows
on:
  push:
    branches:
      - vcpkg
  pull_request:
  release:
    types: ['published']


jobs:
  build:
    name: build (windows)
    runs-on: windows-2022

    steps:
      - name: ğŸ£ Checkout
        uses: actions/checkout@v4

      - name: ğŸ© Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: ğŸ§½ Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: ğŸŒ± Install dependencies and generate project files
        shell: bash
        run: |
          cmake -S . \
                -G Ninja \
                -B build \
                -D VCPKG_TARGET_TRIPLET="x64-windows"

      - name: ğŸŒ‹ Build
        run: |
          cmake --build build
