---
name: ğŸªŸ Windows
on:
  push:
    branches:
      - vcpkg
  pull_request:
  release:
    types: ['published']


jobs:
  build:
    name: build (windows)
    runs-on: windows-2022

    steps:
      - name: ğŸ£ Checkout
        uses: actions/checkout@v4

      - name: Init vcpkg
        uses: ./.github/actions/init-vcpkg
        with:
          vcpkg-version: 2024-01-11

      - name: ğŸ© Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: ğŸ§½ Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: ğŸŒ± Install dependencies and generate project files
        shell: bash
        run: |
          cmake -S . \
                -G Ninja \
                -B build \
                -D WITH_BINDINGS=OFF \
                -D VCPKG_TARGET_TRIPLET="x64-windows" \
                -D VCPKG_INSTALL_OPTIONS="--x-buildtrees-root=C:/src" \
                -D NUGET_USERNAME=kadas-albireo \
                -D NUGET_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ“‘ Upload vcpkg build logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-logs-x64-windows
          path: |
            C:/src/**/*.log

      - name: ğŸŒ‹ Build
        run: |
          cmake --build build

      - if: always()
        uses: m-kuhn/action-tmate@patch-1
